### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by Aaron-Lei** [gregnb/mui-datatables#468] opened 2019-03-06 06:34 UTC
## Expected Behavior

When I sort the first column, the request will be sent to the server, and it shows the new data received from server.
## Current Behavior

In server-side mode, when do sorting, the table will sort the data(previously displayed in the table) first and then it shows the new data received from server-side.
## Steps to Reproduce (for bugs)

`const options = {
            filterType: 'dropdown',
            responsive: "stack",
            download: false,
            print: false,
            selectableRows: false,
            serverSide: true,
            count: reduxState.total,
            page: conditionState.page,
            rowsPerPage: conditionState.pageSize,
            rowsPerPageOptions: [10, 15, 20],

            onChangePage: (currentPage) => {
                pageChange(currentPage);
                asyncLoadData();
            },

            onChangeRowsPerPage: (numberOfRows) => {
                pageSizeChange(numberOfRows);
                asyncLoadData();
            },

            onSearchChange: (searchText) => {

            },

            onColumnSortChange: (changedColumn, direction) => {
                let order = 'desc';
                if (direction === 'ascending') {
                    order = 'asc';
                }
                sortedChange(changedColumn, order);
                asyncLoadData();
            },
        };`

Supposed that I have 100 data in the database. and the ids in the db iare from 1-100 and I will query the data with four params namely page, pageSize, sortColumn, order;
So
1.  load the data from server-side with request url '/getData?page=0&pageSize=4', It all works fine when I do pageChange, pageSizeChange.
2. Sopposed that the data structure is 
[
{"id": 10, "name": test-10},
{"id": 5, "name": test-5},
{"id": 3, "name": test-3},
{"id": 12, "name": test-12},
] 
2. If I want to sort the first column 'id', the request url request '/getData?page=0&pageSize=4&column='id'&order='asc''
The expected result should be 
[
{"id": 1, "name": test-1},
{"id": 2, "name": test-2},
{"id": 3, "name": test-3},
{"id": 4, "name": test-4},
]

BUT, on the ui side, when I click the id column, the data in table FIRST changed to 
[
{"id": 3, "name": test-3},
{"id": 5, "name": test-5},
{"id": 10, "name": test-10},
{"id": 12, "name": test-12},
]
that means the table sort the data in browser memory first.
And then when the request data returned, the table refreshed and display the data received from server-side.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by Aaron-Lei** [comment] 2019-03-06 06:54
@gregnb

**Comment by MBCSDave** [comment] 2019-03-08 16:20
I can reproduce the issue with serverSide: true

**Comment by gregnb** [comment] 2019-03-08 22:10
Can you post a codesandbox showing the issue please?

**Comment by Aaron-Lei** [comment] 2019-03-14 07:43
@gregnb 
It is strange that I can't reproduce it when I used mock data. the codesandbox link is as follows:
https://codesandbox.io/s/rw42z4lw7n

So I only have to reporoduce it by description. Please see the Steps to Reproduce (for bugs) of the issue.

Please let me know if still have any questions
Thanks

**Comment by gabrielliwerant** [comment] 2019-05-24 18:33
@Aaron-Lei You may be able to use `customSort` to hook into the sorting process and do what you need there. See if that works for you.

**Comment by tomgazit** [comment] 2019-08-21 06:49
> @gregnb
> It is strange that I can't reproduce it when I used mock data. the codesandbox link is as follows:
> https://codesandbox.io/s/rw42z4lw7n
> 
> So I only have to reporoduce it by description. Please see the Steps to Reproduce (for bugs) of the issue.
> 
> Please let me know if still have any questions
> Thanks

That's because you're using 2.0.0-beta-51, and the issue occurs only post 2.6.0

**Comment by gabrielliwerant** [comment] 2019-08-22 20:45
@tomgazit Thanks for pointing out the version. That does help me find an potential issue, though I'm not sure if it's the one first posted here.

What I find is that the sort direction is not preserved after the state is updated with the new data. However, that is expected when using `serverside: true`, as that means that the dev takes responsibility for keeping the state up to date. If the sort direction is tracked and passed in when the data updates, then as expected, its state will be maintained. I modified the codesandbox example to demonstrate that (only works for the "Name" column): https://codesandbox.io/s/muidatatables-custom-toolbar-b6vuz?fontsize=14.

One issue I found is that it's not clear from the documentation what `sortDirection` should be used when the sorting should be left untouched. I think that can be improved in the docs as well as the API, to include an option as part of the enum that makes this obvious.

Is there another here that I'm missing?

**Comment by tomgazit** [comment] 2019-08-25 06:55
> @tomgazit Thanks for pointing out the version. That does help me find a potential issue, though I'm not sure if it's the one first posted here.
> 
> What I find is that the sort direction is not preserved after the state is updated with the new data. However, that is expected when using `serverside: true`, as that means that the dev takes responsibility for keeping the state up to date. If the sort direction is tracked and passed in when the data updates, then as expected, its state will be maintained. I modified the codesandbox example to demonstrate that (only works for the "Name" column): https://codesandbox.io/s/muidatatables-custom-toolbar-b6vuz?fontsize=14.
> 
> One issue I found is that it's not clear from the documentation what `sortDirection` should be used when the sorting should be left untouched. I think that can be improved in the docs as well as the API, to include an option as part of the enum that makes this obvious.
> 
> Is there another issue here that I'm missing?

@gabrielliwerant, thanks for the quick reply.
With your reply I understood how to fix the sorting issue I had.

Yes, it is missing from the documentation, so I've added a pull request:
https://github.com/gregnb/mui-datatables/pull/864

**Comment by gabrielliwerant** [comment] 2019-08-25 19:38
Thank you @tomgazit, that's very thoughtful, but it's not quite what I had in mind. I self-assigned this ticket so I could work on it, but it looks like it's past time I set up some contribution guidelines so that people don't get confused! :)

**Closed** 2019-08-29 19:59 UTC
Labels: enhancement
