### ISSUE TITLE
Align text in header and celll by collum

### ISSUE THREAD

**Issue by Vn-ChemGio** [gregnb/mui-datatables#1135] opened 2020-01-04 14:00 UTC
In some cell and header of collum in Material Table
I need align text right (ex: toLocaleDateString, or some data)
But I'''m not found any option to do that
I try  setCellProps: () => ({ align: 'right' }) but it only work with cell in collum
Does Any option to do with header of collum ?
Or best option to make header and cell align right in current collum? 
Thanks !

**Comment by gabrielliwerant** [comment] 2020-01-04 21:37
This is a duplicate of the issue here https://github.com/gregnb/mui-datatables/issues/400, which you can follow to catch up on the latest with this issue. Closing this one to prevent clutter.

**Closed by gabrielliwerant** 2020-01-04 21:37 UTC
Labels: duplicate
