### ISSUE TITLE
sort id problem

### ISSUE THREAD

**Issue by mhmmdakbr** [gregnb/mui-datatables#637] opened 2019-05-23 02:23 UTC
## Expected Behavior
for asc
1
2
3
4

for desc
100
99
98
97

## Current Behavior
This is my result for asc sort for id
![prob3](https://user-images.githubusercontent.com/50288046/58220981-1cb9ec80-7d3b-11e9-928f-7be8c4337bca.PNG)
the result should be
10
11
12

and this is my result for desc sort for id
![prob4](https://user-images.githubusercontent.com/50288046/58221229-fd6f8f00-7d3b-11e9-9353-333856a8ba55.PNG)
the result should be
92
91
89

code for data mapping 
` const data = projects.map(p =>[
       '${p.id}'
    ])`

code for column ID
`const columns = [
      {
        name: "id",
        id: "id",
        label: "ID",
        options: {
          filter: false,
          sort:true,}}, `

| Tech         | Version |
|--------------|---------|
| Material-UI  |    ^3.9.3     |
| MUI-datatables  |    ^2.0.0     |
| React        |     ^16.8.6    |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment] 2019-05-23 04:03
I was unable to reproduce this locally on `2.2.0`. Can you help me reproduce this by providing your data sets and using it break an existing example from this project? Alternatively, you could open up a codesandbox with a broken example.

**Comment by mhmmdakbr** [comment] 2019-05-23 11:24
actually my data sets is from an api , so i fetch it in the root files and i pass it as a props to my table , and then mapping it to data

this is my codesandbox
https://codesandbox.io/embed/vigilant-buck-c8g7u?fontsize=14

sorry for my english

**Comment by gabrielliwerant** [comment] 2019-05-23 18:19
Thank you for providing that.

The problem is that you are mapping the id to a string value: ``${p.id}``, so it is being treated and sorted as such. What you want is to map it as a numerical value: `p.id`. Then sorting will work as you expect.

**Comment by mhmmdakbr** [comment] 2019-05-24 06:06
Yes, it worked. Thank you for your help.

**Comment by mhmmdakbr** [comment] 2019-05-24 06:10
Can i ask your help again ? this is my issue #636 
i want to sort column with array value in it

**Comment by gabrielliwerant** [comment] 2019-05-24 07:04
I responded to the other thread. Did you get what you needed for this issue? Ok if I close it?

**Comment by mhmmdakbr** [comment] 2019-05-24 07:07
Yep you can close it, thank you so much

**Closed** 2019-05-24 07:16 UTC
