### ISSUE TITLE
I am having some buttons inside my datatable. On downloading those table cells are showing as [Object][Object]. Is there any fix for this?

### ISSUE THREAD

**Issue by neenu-n** [gregnb/mui-datatables#459] opened 2019-03-04 06:11 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by neenu-n** [comment] 2019-03-04 06:38
My datatable is something like this.

 <MUIDataTable
                data={this.state.data.map(item => {
                  return [
                   
                      <button
                        key={item.data}
                        onClick={() =>
                          this.showTableDetails()
                        }
                      >
                        {item.data}
                      </button>
                   
                  ];
                })}
                columns={columns}
                options={options}
              />

**Comment by neenu-n** [comment] 2019-03-04 06:43
@diegochavez, Is there any fix for this?

**Comment by neenu-n** [comment] 2019-03-04 06:44
@diegochavez, Is there any fix for this?

**Comment by diegochavez** [comment] 2019-03-04 06:47
Sure there's a fix, but I need to find time during this week, could you replicate your problem on condesandbox, we need to know what version of React you are using and mui-datatables. 
Thanks @neenu-n

**Comment by neenu-n** [comment] 2019-03-04 07:03
Please find the URL below
https://codesandbox.io/s/m4ow4wozzx

Thanks diegochavez

**Comment by neenu-n** [comment] 2019-03-05 11:42
@diegochavez , any updates on the above query?

**Comment by gabrielliwerant** [comment] 2019-03-07 15:31
@neenu-n So, the problem is that I don't think this is the recommended way to add buttons to your columns. A better approach would be to use `customBodyRender` in the column options if you want a button in every row of a particular column. See this for an example: https://github.com/gregnb/mui-datatables/pull/470/commits/da2c12bf2fa897fd1704d7017b8bca743bd23bd8.

You can also use the above pattern to add buttons only to individual rows or cells because you have access to the `rowData` in `tableMeta`.

It's better not to pollute your raw data with non-data styling and html, as this will make it difficult to use that data later for any reason, should you want to access it during other table actions. The `customBodyRender` allows you to change how a cell is rendered without affecting the underlying data, so it seems to exist for this purpose.

At the moment, there is a bug in which missing data fields will cause problems (as in the case where you only want a button to show), but if https://github.com/gregnb/mui-datatables/pull/470 is merged, that will be fixed and you should have no problems using the custom render approach.

**Closed** 2019-04-14 23:24 UTC
