### ISSUE TITLE
Sorting is not working on serverSide and it is always descending because of re-render.

### ISSUE THREAD

**Issue by T-pirithiviraj** [gregnb/mui-datatables#954] opened 2019-09-24 04:45 UTC
Sorting is not working if we have a function onColumnSort function. It always showing descending because of re-render and icon gets disabled.

## Expected Behavior
If we have a server side rendering of dataTable, we have to update the state using columnSort function. There if we make API call it will take sorted data with asc/desc sort icon. 

## Current Behavior
Sorting icon is missing in dataTable and always showing descending.

## Steps to Reproduce (for bugs)

1. In render Make server-side = true.
2.call onColumnSortChange().
3.Make API call to fetch sorted column data there.
4.After receiving data populate in dataTable and click on column to sort, it re-renders and erases sortDirection as well as icon

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.2.1      |
| MUI-datatables  |   2.11.1      |
| React        |  16.8.6      |
| browser      |   chrome      |
| etc          |         |

**Comment by T-pirithiviraj** [comment] 2019-09-24 04:49
Open the console , It is throwing an error as : ```index.js:1446 sortDirection is set for more than one column. Only the first column will be considered.```
My code example: 
```this.state = {
          page: 0,
          count: 1,
          changedColumn: null,
          sortDirection: ['asc','none','none','none','none','none','none', 'none'],```
The column array I used is:
 ```  const columns = [
            {
                name: 'reAlias',
                label: 'Alias',
                options: { sortDirection: this.state.sortDirection[0] }
            },
            {
                name: 'cookieGroup',
                label: 'Group',
                options: { sortDirection: this.state.sortDirection[1] }
            },
            {
                name: 'trackerType',
                label: 'Tracker Type',
                options: { sortDirection: this.state.sortDirection[2] }
            },```

This is my function: 
``` onColumnSortChange: (changedColumn, direction) => {
                console.log(direction)
                let order = 'desc';
                if (direction === 'ascending') {
                    order = 'asc';
                }
                this.onSort(changedColumn, order);
            }```.
the function is :
``` onSort = (changedColumn, sortDirection) => {
        this.setState(
            () => ({
                changedColumn: changedColumn,
                sortDirection : sortDirection
            })
        Here I am making an API call ...
        );```

**Comment by pedroo21** [comment] 2019-09-24 14:19
I believe this is a duplicate of #807 where mui-datatables doesn't preserve the state across server side re-renders.

**Comment by gabrielliwerant** [comment] 2019-09-24 16:50
This also looks like a duplicate of your own issue here https://github.com/gregnb/mui-datatables/issues/947.

**Closed** 2019-09-24 16:50 UTC
Labels: duplicate

**Comment by danielbyun** [comment] 2019-09-29 14:19
Hi, 

then how do we keep and display the change from "asc" to "desc" from the state (given we're keeping track in state) when setting sortDirection for multiple columns give the error that @T-pirithiviraj stated in the question?

**Comment by gabrielliwerant** [comment] 2019-09-29 18:23
There is no such thing as sorting along multiple columns. Any sort on a new column will, by necessity, change the arrangement of other columns in order to order itself. You have to set other columns to `'none'` in order to sort along a new column.
