### ISSUE TITLE
onRowClick and expandableRows not working

### ISSUE THREAD

**Issue by ahmetsezen** [gregnb/mui-datatables#540] opened 2019-04-04 14:25 UTC
i couldn't use onRowClick and expandable rows.
code example :
```
class RaporTable extends React.Component {
  state = {
    columns: [
      {
        name: 'İşlem Tarihi',
        options: {
          filter: true
        }
      },
      {
        name: 'Adı Soyadı',
        options: {
          filter: true,
        }
      },
      {
        name: 'Road',
        options: {
          filter: true,
        }
      },
      {
        name: 'Miktar',
        options: {
          filter: true,
          
        }
      },
    ],
    data: [
      ['22/11/2018', 'Business Analyst', 100, 123],
      ['23/12/2018', 'Business Consultant', 2000, 333],
      ['24/11/2018', 'Attorney', 5000, 445],
      ['25/11/2018', 'Business Analyst', 500, 675],
      ['26/11/2018', 'Business Consultant', 7500, 789],
      ['27/11/2018', 'Business Management Analyst', 9400, 562],
      ['28/11/2018', 'Agency Legal Counsel', 210, 953],
      ['29/11/2018', 'Commercial Specialist', 650, 369],
     
    ]
  }

  render() {
    const { columns, data } = this.state;
    const { classes } = this.props;
    const options = {
      filterType: "dropdown",
      responsive: "stacked",
      filter: false,
      download: false,
      print: false,
      selectableRows: true,
      search: false,
      onRowClick: (row,index)=>{
        alert(row)
        
      }
    };
    return (
      <div className={classes.table}>
        <MUIDataTable
          title="Rapor"
          data={data}
          columns={columns}
          options={options}
         
        />
      </div>
    );
  }
}

RaporTable.propTypes = {
  classes: PropTypes.object.isRequired
};

export default withStyles(styles)(RaporTable);
```

| Tech         | Version |
|--------------|---------|
| Material-UI  |      "@material-ui/core": "^3.9.0",    |
| MUI-datatables  |    "mui-datatables": "^2.0.0-beta-1",     |
| React        |    "react": "^16.6.0",     |
| browser      |    Chrome     |
| etc          |         |

**Comment by wdh2100** [comment] 2019-04-08 04:27
https://codesandbox.io/s/my73nr7q69?fontsize=14

https://stackoverflow.com/questions/31079081/programmatically-navigate-using-react-router

:D

**Comment by gabrielliwerant** [comment] 2019-05-10 07:29
Closing, as this is a duplicate of https://github.com/gregnb/mui-datatables/issues/553. Also, I believe this functionality is now working, but if not, you can continue in the other issue thread.

**Closed by gabrielliwerant** 2019-05-10 07:29 UTC
Labels: duplicate
