### ISSUE TITLE
onRowClick triggers when row is selected

### ISSUE THREAD

**Issue by jfederer** [gregnb/mui-datatables#553] opened 2019-04-09 19:04 UTC
## Expected Behavior
I'd like onRowClick to run when I click a row...and I'd like onRowSelect to run when I click one (or multiple) checkboxes.   Specifically, I want clicking a row to run a function that does NOT run when someone clicks a checkbox to select that row.

## Current code: 
class EventsManager extends React.Component {
	constructor(props) {
		super(props);

		this.options = {
			filterType: 'checkbox',
			print: false,
			download: false,
			onRowClick: this.onRowClick,
			onRowsSelect: this.onRowsSelect
		};

		console.log("Sampling Events: ", this.props.samplingEvents);
	}

	onRowClick = (rowData: string[], rowMeta: { dataIndex: number, rowIndex: number }) => {
		console.log("----RowClick");
		console.log("rowData: ", rowData);
		console.log("rowMeta: ", rowMeta);
	}

	onRowsSelect = (curRowSelected, allRowsSelected) => {
		console.log("---RowSelect")
		console.log("Row Selected: ", curRowSelected);
		console.log("All Selected: ", allRowsSelected);
	}

	render() {
		return <MUIDataTable
			title={"Events Manager"}
			data={data}
			columns={columns}
			options={this.options}
		/>
	}
}

1) Click the checkbox...
2) you'll see that "RowClick" is triggered.

**Comment by wdh2100** [comment] 2019-04-11 04:08
#456

**Comment by jfederer** [comment] 2019-04-22 16:39
I don't see how #456 is related?

When I click the checkbox, I don't want the "onRowClick" to trigger... but it does.

For example, when I click a row (NOT the checkbox) I want to do action XYZ...
when I click a checkbox to SELECT a row, I do NOT want to do action XYZ.

Does this help clarify?

**Comment by gabrielliwerant** [comment] 2019-05-07 23:58
@jfederer Is this still an issue on `master`? I tested locally with the `selectable-rows` example and it looks like it works as expected to me:

![capture](https://user-images.githubusercontent.com/1779564/57340128-882c7900-7102-11e9-8a37-6d2c686b54a6.gif)

**Comment by gabrielliwerant** [comment] 2019-05-21 04:14
Closing, as issue appears fixed. Please open a new issue with the steps to reproduce if this issue appears again.

**Closed by gabrielliwerant** 2019-05-21 04:14 UTC

**Comment by zbubric** [comment] 2019-07-19 10:12
I can confirm this issue:
Version: 2.6.4
Codebase: own code based on seletable-rows example

Expected behavior:
click on checbox should fire onRowsSelected
click on row (anywhere beside checkbox) should fire onRowClick

Actual behavior:
if selectableRowsOnClick: true: click on checkbox or any other part of row fires onRowsSelected, onRowClick not fired
if selectableRowsOnClick: false: click on checkbox or any other part of row fires onRowsClik, onRowsSelected not fired, row is not selected

**Comment by gabrielliwerant** [comment] 2019-07-19 17:40
@zbubric What you are describing is intentional behavior. A row selection is treated differently than a row click, even when the row selection is triggered by a click.

**Comment by plyskor** [comment] 2020-09-22 19:20
Is this issue corrected in some version? I also have the same problem. Following what @gabrielliwerant said, onRowClick should not be called when the selection checkbox is clicked (the event's propagation should be stopped).

I have this problem in version 3.1.3

**Comment by patorjk** [comment] 2020-09-22 19:38
I would expect @zbubric's interpretation to be correct, but his actual results reflect how the code is setup:

https://github.com/gregnb/mui-datatables/blob/master/src/components/TableBody.js#L185

However, I believe this can be worked around by using the setRowProps options and the onMouseUp, example:

https://codesandbox.io/s/muidatatables-custom-toolbar-forked-lm65g?file=/index.js

Also, as can be seen in that example, onRowClick does not execute.

**Comment by plyskor** [comment] 2020-09-22 21:22
console is only showing click up! for me

**Comment by plyskor** [comment] 2020-09-22 21:25
That is the issue for me, since onRowClick get useless because of the selection, how can we use both features at the same time? how can I have a function for when I select a row, and a different function for when I click anywhere else on the row (but not in the checkbox)?

**Comment by patorjk** [comment] 2020-09-22 21:45
Did you try the codesandbox? I showed one way of doing that. In the console the onMouseUp function executes when a row is clicked.

**Comment by plyskor** [comment] 2020-09-22 21:56
It actually shows "mouse up!" all the time, even when I click in the checkbox. So I don't have a separate behavior

**Comment by DarkMagician081** [comment] 2020-09-25 07:29
Yeah the onMouseUp function executes, but is there any way of executing the onRowClick function as well?
