### ISSUE TITLE
View Columns and Filter Table not showing

### ISSUE THREAD

**Issue by zwk5004** [gregnb/mui-datatables#680] opened 2019-06-07 15:40 UTC
The buttons for showing View Column and Filter Table are not showing the dropdown for them.  Had debugger open and the <span> gets some child elements but they disappear before it can be expanded.  Looks similar to a previous issue

## Expected Behavior

Clicking View Columns or Filter Table button should show the dropdown for selection.

## Current Behavior

Clicking View Columns or Filter Table button does not show the dropdown for selection.

## Steps to Reproduce (for bugs)

```
const options = {
    filterType: 'dropdown',
    responsive: 'scroll',
    selectableRows: false,
}

export function buildTableData(columns, positions) {
    return {
        columns,
        options,
        data: positions
    }
}

render() {
   return <MUIDataTable {...buildTableData(columns, positions || [])} />
}
```

1. Click Button
2. Nothing happens afterwards in browser
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.9.3     |
| MUI-datatables  |     2.2.0  and 2.3.0   |
| React        |    16.8.6     |
| browser      |    Chrome - Version 74.0.3729.169 (Official Build) (64-bit)     |
| etc          |         |

**Comment by gabrielliwerant** [comment] 2019-06-07 23:46
Hello @zwk5004. I'm unable to reproduce this issue. It may depend on your data or some other specific thing that isn't being shown here. Can you reproduce this issue in an existing example or via codesandbox so that I can interact with it?

**Comment by gabrielliwerant** [comment] 2019-07-02 05:43
Closing, as this issue has been open for over 3 weeks without the ability to reproduce. If the issue returns, please open a new issue with a specific example, ideally in codesandbox or someplace where it can be interacted with and verified.

**Closed by gabrielliwerant** 2019-07-02 05:43 UTC
Labels: needs verification
