### ISSUE TITLE
It doesn't work with react typescript

### ISSUE THREAD

**Issue by normanaranez** [gregnb/mui-datatables#259] opened 2018-11-07 04:17 UTC
I tried to import the mui-datables in react that typescript

## Expected Behavior
the file should be imported in the react project

## Current Behavior
cant find the file event the import syntax was right

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |   2.0.0-beta-38      |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by ideoclickVanessa** [comment] 2018-11-08 20:45
I'm currently using `2.0.0-beta-38` in my Typescript app using the following import:
`import MUIDataTable, { MUIDataTableColumn, MUIDataTableOptions } from "mui-datatables";`

That said, there does seem to be a console.log() statement left in the source code:
```
}, {
    key: "isRowSelected",
    value: function value(e) {
      var t = this.props.selectedRows;
      return !(!t.lookup || !t.lookup[e]);
    }
  }, {
    key: "render",
    value: function value() {
      var n = this,
          e = this.props,
          t = e.classes,
          r = e.columns,
          l = e.options,
          a = this.buildRows();
      return console.log(l), React.createElement(TableBody, null, a ? a.map(function (e, a) {
        var t = e.data,
            o = e.dataIndex;
        return React.createElement(MUIDataTableBodyRow$1, {
          options: l,
          rowSelected: !!l.selectableRows && n.isRowSelected(o),
          onClick: l.onRowClick ? l.onRowClick.bind(null, t, {
            rowIndex: a,
            dataIndex: o
          }) : null,
          id: "MUIDataTableBodyRow-" + o,
          key: a
        }, !!l.selectableRows && React.createElement(MUIDataTableSelectCell$1, {
          onChange: n.handleRowSelect.bind(null, {
            index: n.getRowIndex(a),
            dataIndex: o
          }),
          fixedHeader: l.fixedHeader,
          checked: n.isRowSelected(o)
        }), t.map(function (e, t) {
          return "true" === r[t].display && React.createElement(MUIDataTableBodyCell$1, {
            dataIndex: o,
```

**Comment by abstruse9** [comment] 2018-11-09 05:00
Yes, there is a `console.log` in the source code. I noticed it too!

I am currently using this library with Typescript. I guess you missed to define your typings file.

**Comment by gregnb** [comment] 2018-11-09 11:52
It was removed in -39

**Comment by Favna** [comment] 2019-01-29 14:02
@ideoclickVanessa If you can confirm that those types from the gist work properly could you submit them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) in lieu of them being added to the project by default? 

I'd do it myself but I have no React in TypeScript environment set up as of yet as the application I work on will be transferring only in the coming future.

**Comment by Favna** [comment] 2019-01-29 16:13
Update: Type definitions have been submitted to DefinitelyTyped. 

Hopefully they will be merged there soon, after which we can use `npm install @types/mui-datatables` 

PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32591

**Comment by Favna** [comment] 2019-01-30 06:58
Another update: the aforementioned PR has been merged. Typings should  soon be available through `npm install @types/mui-datatables`. I'd say this issue can be closed. 

Writing at 07:00 (AM) UTC January 30th - I just checked NPM and the types have not yet been auto published. Not sure how quick DefinitelyTyped's publishing turnover is.

**Comment by deskoh** [comment] 2019-02-12 04:43
The `import` for `mui-datatables` does not work for `typescript@3.2.4` and `mui-datatables@2.0.0-beta-54`. It returned undefined. Works well if file is renamed from `.tsx` to `.js`.

```
import * as React from 'react';
import MUIDataTable from 'mui-datatables';

const columns = ['Name', 'Company', 'City', 'State'];

const data = [
 ['Joe James', 'Test Corp', 'Yonkers', 'NY'],
 ['John Walsh', 'Test Corp', 'Hartford', 'CT'],
 ['Bob Herm', 'Test Corp', 'Tampa', 'FL'],
 ['James Houston', 'Test Corp', 'Dallas', 'TX'],
];

// undefined for .tsx
console.log(MUIDataTable);

const TestTable = () => (
  <MUIDataTable
    title={'Employee List'}
    data={data}
    columns={columns}
  />

);

export default TestTable;
```

**Comment by Favna** [comment] 2019-02-12 05:59
@deskoh please be dure to add @types/mui-datatables

Furthermore if you want actual support also provide the following:

- your tsconfig.json
- your package.json (specifically the dependencies and devDependencies fields)

**Comment by deskoh** [comment] 2019-02-12 09:44
Same issue. Reproduced problem at repo here: https://github.com/deskoh/mui-datatables-ts

**Comment by Favna** [comment] 2019-02-12 15:41
Send a new PR to DefinitelyTyped to update for 2.0.0-beta-54: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32998

---

@deskoh I can't make any promises because I run a busy schedule but if I get some time I'll check your code and see if I can figure it out.

**Comment by deskoh** [comment] 2019-02-13 09:03
@Favna Found the fix. `tsconfig.json` requires `esModuleInterop` to be set to true for `import` of `mui-datatables` to work.

```json
{
  "compilerOptions": {
    ...
    "esModuleInterop": true
  },
  ...
}
```

More details on the `esModuleInterop` flag can be found [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html).

**Comment by kieranbop** [comment] 2019-06-14 04:50
Even with `esModuleInterop` set to true and both packages
` "@types/mui-datatables": "^2.1.2"` &&  `"mui-datatables": "^2.4.0"` I cannot utilise any of the options as they are not assignable.

**Comment by Favna** [comment] 2019-06-14 07:15
@kieranbop please share code snippets and exact errors, or publish the code on github / gist and share links. We can’t help otherwise.

**Comment by kieranbop** [comment] 2019-06-14 10:07
I cleared my cache and did a full re-install and it is compiling again. I'd recommend this is now closed.

**Closed** 2019-06-14 18:53 UTC
Labels: question
