### ISSUE TITLE
TypeScript - Show all rows on the current page of the table without a vertical scroll bar when using 'responsive="scroll"' option.

### ISSUE THREAD

**Issue by HyungNLee** [gregnb/mui-datatables#580] opened 2019-04-26 20:02 UTC
I was wondering if it is possible to add the ability to show all current rows on the page of the table without a vertical scroll bar when using the responsive="scroll" option using Typescript. Currently the height of the table is set at a fixed value.

I'm using Typescript and since Mui ThemeOptions.overrides does not contain a definition for Mui Datatables it won't let me override the height. 

I'm avoiding use the stacked option because it causes an issue with the paper component from material ui when horizontally scrolling, causing it to end where the scrolling begins and showing what looks like an x axis overflow.

Thank you!

**Comment by gabrielliwerant** [comment] 2019-04-26 23:16
Personally, I'm not a Typescript guy, so I'm of limited help here, but I'm pretty sure the material-ui guys have thought about this from a typescript perspective, so you might find help there. Maybe this will be of some help? https://material-ui.com/guides/typescript/

**Comment by ideoclickVanessa** [comment] 2019-05-01 15:32
Could the max-height default simply be set to 100% by default and perhaps those that want to not have the 100% default could set a custom property? Thus, avoiding the whole need to override the MUI Theme Options.

**Comment by petrbela** [comment] 2019-05-06 23:33
Removed TypeScript from the title since this is not a TypeScript-specific question.

First of all, this should really be [fixed in the library](https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L32).

A temporary workaround for this issue is to override the `responsiveScroll`. You can then use this `DataTable` component instead of `MUIDataTable`.

```jsx
import React from 'react'
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core/styles'
import MUIDataTable from 'mui-datatables'

export default function DataTable(props: any) {
  const theme = createMuiTheme({
    overrides: {
      MUIDataTable: {
        responsiveScroll: {
          overflowX: 'none',
          height: 'auto',
          maxHeight: 'auto',
        },
      },
    },
  })

  return (
    <MuiThemeProvider theme={theme}>
      <MUIDataTable {...props} />
    </MuiThemeProvider>
  )
}
```

Alternatively, to apply this change globally, you can wrap your entire (somewhere in `App` or `index`) with the `MuiThemeProvider`, and continue using `MUIDataTable`.

**Comment by gabrielliwerant** [comment] 2019-05-07 00:10
@petrbela This question has come up many times before, but it's different with Typescript. It's not as simple to override styles, as this question points out.

It's not clear, to me at any rate, which default setting would be better. Both full height and maxHeight have their merits, so no matter what the default setting is, there will be people that need to override the style setting. Perhaps there should be additional responsive options like, `scrollMaxHeight` and `scrollFullHeight` instead of just `scroll`.

In the mean time, I think it's worth keeping this question phrased as is in case anyone has specific experience with performing this kind of override in a Typescript setting.

**Comment by petrbela** [comment] 2019-05-07 00:29
Ah, you're right, sorry I just skimmed the text and didn't notice it.

It almost feels like the issue is in [material-ui itself](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/overrides.d.ts#L96) but unfortunately, TypeScript only supports extension through generics (which would work for a single case) but not through a union (which would be needed to support multiple mui-extending libraries).

As for the wording of the question, the issue is not really about scroll bars but about overriding styles in general (not sure if there's an issue for that already).

**Comment by gabrielliwerant** [comment] 2019-05-07 19:59
@petrbela No worries, thanks for chiming in! I'm certainly out of my element with ts, but if it can't be elegantly done with it, and there's continual need for specific overrides, it may be worth considering additional options for the specific use case mentioned here (though I agree the ts overrides problem will not be limited to this use case).

Haha, yes, there's always ignore! Certainly better than not being able to proceed at all.

**Comment by petrbela** [comment] 2019-05-07 22:14
Well. I was researching some totally unrelated stuff and realized TypeScript already supports [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

So, long story short, this is the gist:

```ts
import { Overrides } from '@material-ui/core/styles/overrides'

declare module '@material-ui/core/styles/overrides' {
  interface ComponentNameToClassKey {
    MuiDataTable?: {  // this should obviously use the types in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mui-datatables/index.d.ts
      responsiveScroll: {
        height?: string
        maxHeight?: string
      }
    }
  }
}
```

If I get a bit of time later I can turn this into a PR.

Side note, MUI's documentation recommends customizing the styles on the [createMuiTheme level](https://material-ui.com/guides/typescript/#customization-of-theme) but that would require some breaking changes. The proposed solution should work just as well.

**Comment by ideoclickVanessa** [comment] 2019-07-01 14:49
The above type file didn't work for me. I needed to use this:
```
import { ComponentNameToClassKey } from '@material-ui/core/styles/overrides'

declare module '@material-ui/core/styles/overrides' {
    type MUIDataTableClassKey =
        | "responsiveScroll";

    type MUIDataTableHeadCellClassKey =
        | "root"
        | "toolButton";

    interface ComponentNameToClassKey {
        MUIDataTable: MUIDataTableClassKey;
        MUIDataTableHeadCell: MUIDataTableHeadCellClassKey;
    }
}
```
which then allowed me to define the overrides in the createMuiTheme like so:
```
const theme = createMuiTheme({
    "overrides": {
        "MUIDataTable": {
            "responsiveScroll": {
                "maxHeight": "unset",
            },
        },
        "MUIDataTableHeadCell": {
            "root": {
                "whiteSpace": "nowrap",
            },
            "toolButton": {
                "height": "unset",
            },
        },
        "MuiListItem": {
            "root": {
                "&$selected": {
                    "backgroundColor": "#2196F3",
                    "color": "#FFF",
                },
                "&$selected:focus": {
                    "backgroundColor": "#2196F3",
                    "color": "#FFF",
                },
                "&$selected:hover": {
                    "backgroundColor": "#2196F3",
                    "color": "#FFF",
                }
            }
        },
    },
    "palette": {
        "primary": {
            "contrastText": "#1E1D1B",
            "main": "#F9CB3F",
        },
        "secondary": {
            "contrastText": "#FFF",
            "main": "#2196F3",
        },
    },
    "props": {
        "MuiGrid": {
            "spacing": 1,
        }
    },
});
```

**Comment by JReinhold** [comment] 2019-09-01 10:23
As of [V2.10.0](https://github.com/gregnb/mui-datatables/tree/2.10.0) it is now possible to use the prop `responsive="scrollFullHeight"` to make the table full height and a scroll behavior at the same time. That should fix the issue.

See https://github.com/gregnb/mui-datatables/pull/867

**Closed** 2019-09-01 18:44 UTC
Labels: question

**Comment by jlucier** [comment] 2019-09-10 06:45
@JReinhold 
With `scrollFullHeight` I'm seeing the table at full height (great), but I'm not seeing horizontal scrolling for my tables. Is this option supposed to cause the table to scroll horizontally when it's overflowing?

I'm on 2.10.2.

**Comment by gabrielliwerant** [comment] 2019-09-10 22:19
@jlucier Can you open up a new issue for that? It's a bug.

**Comment by gabrielliwerant** [comment] 2019-09-11 01:24
@jlucier Nevermind, already merged!

**Comment by kenjoegolo** [comment] 2019-10-10 18:10
> @JReinhold
> With `scrollFullHeight` I'm seeing the table at full height (great), but I'm not seeing horizontal scrolling for my tables. I'm concerned this is related to some kind of inherited styles similar to #732, however it still works (albeit with deprecation warnings) using the [workaround](https://github.com/gregnb/mui-datatables/issues/580#issuecomment-489824576) from @petrbela.
> 
> I'm on 2.10.2.

I'm also facing this issue. I'm using version `2.11.1`

**Comment by jlucier** [comment] 2019-10-11 00:12
@kenjoegolo As far as I can tell, it's fixed in 2.12.0

**Comment by kenjoegolo** [comment] 2019-10-11 04:03
@jlucier I'm trying to follow this scroll behavior on latest version 2.12.0

https://codesandbox.io/s/muidatatables-custom-toolbar-9u979

but what happens on my side is there is no vertical scroll on my table.

**Comment by jlucier** [comment] 2019-10-11 04:24
@kenjoegolo You don't want `scrollFullHeight` then. From the docs

> responsive: Enable/disable responsive table views. Options: 'stacked', 'scrollMaxHeight' (limits height of table), 'scrollFullHeight' (table takes on as much height as needed to display all rows set in rowsPerPage)

Seems like you want to use `scrollMaxHeight`.
