### ISSUE TITLE
Uncaught Error: Provided options.page of `6` is greater than the total available page length of `1`

### ISSUE THREAD

**Issue by amrithds** [gregnb/mui-datatables#370] opened 2019-01-16 12:35 UTC
Fatal error is generated and page stops rendering when the page number is greater than 1 and the filter is applied which results in less number of pages than the current options.page value. 

mui-datatables Version : 2.0.0-beta-52

## Expected Behavior

The expected behavior is the page should reset to 1 or to the last page of total available page.

## Current Behavior
Fatal error
Uncaught Error: Provided options.page of `6` is greater than the total available page length of `1`

## Steps to Reproduce (for bugs)
1. Unset all filters
2. Go to page 5 (Greater than 1)
3. Apply select filters on the column so that result is having 1 page
4. Check the console

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.0.0     |
| MUI-datatables  |    2.0.0-beta-52     |
| React        |    16.3.0     |
| browser      |    chrome     |

**Comment by dhanalakshmimuthusamy** [comment] 2019-02-19 06:47
HI
I also got the same error while applying the filtering for the MUI datatables .Is there there any fix for that?

mui-datatables Version : 2.0.0-beta-54

## Environment
Tech	Version
Material-UI	3.9.0
MUI-datatables	2.0.0-beta-54
React	16.7
browser	chrome

**Comment by vmf91** [comment] 2019-02-28 01:07
I also got the same error with the current environment:

| Tech         | Version |
|--------------|---------|
| Material-UI  |     3.1.0    |
| MUI-datatables  |   2.0.0-beta.56      |
| React        |    16.5.2     |
| browser      |    Chrome     |

**Comment by ericpyle** [comment] 2019-03-21 20:10
I got this as well :( with 

material-ui|3.9.2
mui-datatables | 2.0.0-beta.58
react | 16.3.0
browser | chrome

**Comment by ericpyle** [comment] 2019-03-25 15:50
by the way, I haven't actually been able to reproduce this 100% of the time. Sometimes I can seemingly follow the same steps and it doesn't crash. @vmf91 @dhanalakshmimuthusamy @amrithds do you know the exact minimal steps needed to reproduce this crash reliably? Or might this be a race condition?

I would like to test this workaround but until I can find a relative path, I am not sure it works.

>   componentDidCatch(error, info) {
>     // Display fallback UI
>     this.setState({ page: 0 });
>   }
> 

in render()

> const options = {
>      ...
>       page: this.state.page
>     };
>     return (
>       <Paper className={classes.root}>
>         <MUIDataTable
>           ...
>           options={options}
>         />
>       </Paper>
>     );

**Comment by QuentinChevance** [comment] 2019-06-03 13:24
Hello, just got the same error :(
Do you plan on fixing this issue soon ?
Or is there a workaround I could add to my code to fix the error ?

Environment
--
| Tech           | Version |
|----------------|---------|
| Material-UI    | 3.9.3   |
| MUI-datatables | 2.3.0   |
| React          | 16.8.6  |
| browser        | Chrome  |

**Comment by gabrielliwerant** [comment] 2019-06-03 17:45
I can't verify a crash, but I can verify an issue where the filtered results don't show on the table because they are on page 0, not the page currently set. Does that match issue discussed here?

**Comment by QuentinChevance** [comment] 2019-06-04 07:36
It might be a solution to set the current page to 0 when we filter the table results.
For now, I added `getDerivedStateFromError` to my component to prevent my app from crashing.

**Comment by gabrielliwerant** [comment] 2019-06-20 04:37
Fix for this issue is now in `2.5.0` thanks to #685.

**Closed by gabrielliwerant** 2019-06-20 04:37 UTC
Labels: bug
