### ISSUE TITLE
custom Toolbar  when trigger onClick for action to popup modal data in the table disappear

### ISSUE THREAD

**Issue by Teslima02** [gregnb/mui-datatables#761] opened 2019-07-10 18:24 UTC
custom Toolbar  when trigger onClick for action to popup modal, datas in the table disappear please help. Thanks

```
const options = {
    filterType: 'checkbox',
    responsive: 'scroll',
    customToolbar: () => {
        return (
            <Tooltip title={"New Product"}>
                <IconButton className={classes.iconButton} onClick={() => openNewBondsDialog()}>
                    <AddIcon className={classes.deleteIcon} />
                </IconButton>
            </Tooltip>
        );
    }
};

```

This's the table component
```
import React, { Component } from 'react';
import { FormControlLabel, Switch, withStyles, Icon, IconButton, Tooltip } from '@material-ui/core';
import AddIcon from "@material-ui/icons/Add";
import { NavLink, withRouter } from 'react-router-dom';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import MUIDataTable from "mui-datatables";
import * as Actions from '../../store/actions';
import AddButton from './AddButton';

const styles = theme => ({
    listItem: {
        color: 'inherit!important',
        textDecoration: 'none!important',
        height: 40,
        width: 'calc(100% - 16px)',
        borderRadius: '0 20px 20px 0',
        paddingLeft: 24,
        paddingRight: 12,
        '&.active': {
            backgroundColor: theme.palette.secondary.main,
            color: theme.palette.secondary.contrastText + '!important',
            pointerEvents: 'none',
            '& .list-item-icon': {
                color: 'inherit'
            }
        }
    }
});

class BondsProductsList extends Component {

    handleClick = () => {
        this.props.openNewBondsDialog();
        // console.log("clicked on icon!");
      }

    render() {
        const { openNewBondsDialog, openEditBondsDialog, bondsProduct, data, getBondsDetails, classes } = this.props;

        const columns = [
            {
                name: "id",
                label: "S/N",
                options: {
                    filter: true,
                    customBodyRender: (value, tableMeta) => {
                        return (
                            <FormControlLabel
                                label={tableMeta.rowIndex + 1}
                                control={
                                    <Icon></Icon>
                                }
                            />
                        );

                    }
                }
            },
            {
                name: "initialVolume",
                label: "Initial Volume",
                options: {
                    filter: true,
                    sort: true,
                }
            },
            {
                name: "totalVolume",
                label: "Total Volume",
                options: {
                    filter: true,
                    sort: false,
                }
            },
            {
                name: "couponRate",
                label: "Coupon Rate",
                options: {
                    filter: true,
                    sort: false,
                }
            },
            {
                name: "yieldRate",
                label: "Yield Rate",
                options: {
                    filter: true,
                    sort: false,
                }
            },
            {
                name: "cleanPrice",
                label: "Clean Price",
                options: {
                    filter: true,
                    sort: false,
                }
            },
            {
                name: "maturity",
                label: "Maturity",
                options: {
                    filter: true,
                    sort: false,
                }
            },
            {
                name: "id",
                label: "Edit",
                options: {
                    filter: true,
                    customBodyRender: (value, tableMeta) => {
                        return (
                            <FormControlLabel
                                label="Edit"
                                control={
                                    <Icon>create</Icon>
                                }
                                onClick={evt => {
                                    evt.stopPropagation()
                                    // evt.preventDefault()
                                    //TODO: userId hard coded here base on array index 'tableMeta.rowData[4]'
                                    // this.logClick(value, evt.target.value, tableMeta);
                                    openEditBondsDialog(tableMeta.rowData);
                                    // openEditTbillsDialog(this.state);
                                    getBondsDetails(value);
                                    // updateProduct(tableMeta.rowData);
                                }}
                            />
                        );

                    }
                }
            },
        ];

        const options = {
            filterType: 'checkbox',
            responsive: 'scroll',
            customToolbar: () => {
                return (
                    <Tooltip title={"New Product"}>
                        {/* <IconButton className={classes.iconButton} onClick={this.handleClick}> */}
                        <IconButton className={classes.iconButton} onClick={() => openNewBondsDialog()}>
                            <AddIcon className={classes.deleteIcon} />
                        </IconButton>
                    </Tooltip>
                );
            }
        };

        return (
            <div>
                <MUIDataTable
                    title={"Bonds"}
                    data={data}
                    columns={columns}
                    options={options}
                />
            </div>
        );
    }
}

function mapDispatchToProps(dispatch) {
    return bindActionCreators({
        openNewBondsDialog: Actions.openNewBondsDialog,
        openEditBondsDialog: Actions.openEditBondsDialog,
        getBondsDetails: Actions.getBondsDetails,
    }, dispatch);
}

function mapStateToProps({ bondsApp }) {
    return {
        bondsProduct: bondsApp.bonds.bondsProduct
    }
}

export default withStyles(styles, { withTheme: true })(withRouter(connect(mapStateToProps, mapDispatchToProps)(BondsProductsList)));
```

This's the action
`
export function openNewBondsDialog() {
    return {
        type: OPEN_NEW_BONDS_DIALOG
    }
}
`

This's the reducer
```
import * as Actions from '../actions';
import _ from 'lodash';

const initialState = {
    bondsProducts: [],
    bondsProduct: '',
    bondsDialog: {
        type: 'new',
        props: {
            open: false
        },
        data: null
    }
};

const bondsReducer = function (state = initialState, action) {
    switch (action.type) {
        case Actions.GET_BONDS_PRODUCT:
            {
                return {
                    ...state,
                    bondsProducts: action.payload,
                };
            }
        case Actions.GET_BONDS_DETAILS:
            {
                return {
                    ...state,
                    bondsProduct: action.payload,
                };
            }
        case Actions.OPEN_NEW_BONDS_DIALOG:
            {
                return {
                    bondsDialog: {
                        type: 'new',
                        props: {
                            open: true
                        },
                        data: null
                    }
                }
            }
        case Actions.CLOSE_NEW_BONDS_DIALOG:
            {
                return {
                    bondsDialog: {
                        type: 'new',
                        props: {
                            open: false
                        },
                        data: null
                    }
                }
            }
        case Actions.OPEN_EDIT_BONDS_DIALOG:
            {
                return {
                    bondsDialog: {
                        type: 'edit',
                        props: {
                            open: true
                        },
                        data: action.data
                    }
                }
            }
        case Actions.CLOSE_EDIT_BONDS_DIALOG:
            {
                return {
                    bondsDialog: {
                        type: 'edit',
                        props: {
                            open: false
                        },
                        data: null
                    }
                }
            }
        default:
            {
                return state;
            }

    }
}
export default bondsReducer;
```
``
The moment this action triggered this openNewBondsDialog() will disappear the current data in the table

| Tech         | Version |
|--------------|---------|
| Material-UI  |        3.9.2 |
| MUI-datatables  |        2.5.1 |
| React        |         16.8.3|
| browser      |         chrome|
| etc          |         |``

**Comment by gabrielliwerant** [comment] 2019-07-10 18:52
Unfortunately, there is not enough information given here to reproduce the issue. Can you please provide a full working example, preferably in something like codesandbox? If you can do that, I will be happy to take a look.

**Comment by Teslima02** [comment] 2019-07-10 19:19
Thank you @gabrielliwerant  have updated the code

**Comment by gabrielliwerant** [comment] 2019-07-10 21:29
Thanks for the attempt, but I actually need something more stripped down, and far simpler, that will demonstrate the issue. The minimal case, essentially. You are using a lot of code I'd have to copy and paste into a local testing environment, and it's using redux, which I would then need to install and set up. This is part of why I asked for codesandbox, because the example would then be running for me, but ultimately, to demonstrate that the issue is with the table and not additional technology and code, it would be best to start from a core example from the project, and add minimal changes until you reach the breaking state you see. I would also stick with vanilla react, for demonstration purposes, as adding redux makes this much harder to verify and work with.

**Comment by Teslima02** [comment] 2019-07-11 10:36
Thanks @gabrielliwerant am able to resolved the issue now the mistake was from me. I was not sending the initialsState in reducer moment after the action get triggered.
Thanks appreciate you for the support.
```
const initialState = {
    bondsProducts: [],
    bondsProduct: '',
    bondsDialog: {
        type: 'new',
        props: {
            open: false
        },
        data: null
    }
};
```

**Comment by gabrielliwerant** [comment] 2019-07-12 03:25
No problem, and I'm glad it worked out for you!

I assume it's ok to close the issue?

**Comment by Teslima02** [comment] 2019-07-12 18:37
Yes

**Closed** 2019-07-12 20:54 UTC
Labels: needs verification
