### ISSUE TITLE
modal for filter wont open

### ISSUE THREAD

**Issue by mamdasan** [gregnb/mui-datatables#616] opened 2019-05-13 11:36 UTC
the modal for filtering and deleting columns wont open in the 2.1.0 version, the 2.0.0 version is working properly.

**Comment by NickTomlin** [comment] 2019-05-13 16:43
Here's a [reproduction](https://codesandbox.io/s/w6wrmv7y7k?fontsize=14) in codesandbox using `mui-datatables@2.1.0` and a recent `create-react-app` (with `react` and `react-dom` at e`16.8.6`).


I am not able to reproduce this by bumping `mui-datatables` to `2.1.0` in the existing codesandbox examples, so it could be something that has changed in react core? @mamdasan are you able to reproduce using an older sandbox?

**Comment by gabrielliwerant** [comment] 2019-05-14 04:09
This is a dupe of this issue https://github.com/gregnb/mui-datatables/issues/600. There is PR open for it, but in the mean time, you can fix it locally by using material-ui version `3.2.0`.

**Comment by dandrei** [comment] 2019-05-15 08:44
Just a quick heads up: using `@material-ui/core` `4.0.0-beta.2`, the filtering modal works in `mui-datatables` `2.0.0`, but stops working in `2.1.0`.

(I know v4 isn't officially supported, just letting you know what works and what doesn't)

**Comment by gabrielliwerant** [comment] 2019-05-16 06:27
Closed via https://github.com/gregnb/mui-datatables/pull/606

**Closed by gabrielliwerant** 2019-05-16 06:27 UTC
Labels: duplicate
