### ISSUE TITLE
Date sorting is not working correctly.

### ISSUE THREAD

**Issue by DhruvSakhiya** [gregnb/mui-datatables#1205] opened 2020-02-29 05:56 UTC
My date format is MM/dd/yyyy and custom sorting is not working.

## Expected Behavior

on default sort date column and it is descending order 
 

## Current Behavior
Not Working even and i simply wrote options:{sortDirection: 'desc'}.It shows wrong result.

## Steps to Reproduce (for bugs)

In date column i provided options:
 options:{
         Sort: (data, colIndex, order) => {
         return data.sort((a, b) => {
           return (a.data[colIndex].length < b.data[colIndex].length ? -1: 1 ) * (order === 'desc' ? 1 : -1);
         });
         },
      }

**Comment by gabrielliwerant** [comment] 2020-02-29 12:18
I'm not sure what API you're attempting to use. In the main options, there is a `customSort` function. In the column options, there is a `sort` which is a boolean. It looks like you are not using the correct API.

**Comment by DhruvSakhiya** [comment] 2020-02-29 14:04
Sorry i forgot to add customSort full just copied sort. ,I used customSort for this

**Comment by gabrielliwerant** [comment] 2020-02-29 16:13
What is not working? I don't know what it is you're trying to accomplish. Copy and pasting demonstration logic into your app is unlikely to match the behavior you want. Are you saying nothing happens at all? If so, I cannot verify that in the example in this repo, as it looks like it's working to me. You would have to produce a simple, broken example in codesandbox so I can review it.

**Comment by gabrielliwerant** [comment] 2020-02-29 16:15
Also, I can't tell where you put your options. As I explained, there are main options and column options. When you say you provided options in "date column" it makes me think you used column options, which is incorrect.

**Comment by DhruvSakhiya** [comment] 2020-03-03 09:06
https://codesandbox.io/s/stupefied-volhard-jntyu?fontsize=14&hidenavigation=1&theme=dark

this is my codesandbox url in which date sorting is not working correctly. you can see it.

**Comment by gabrielliwerant** [comment] 2020-03-03 11:33
@DhruvSakhiya Ok, one more try, and then I have to close this issue.

Your codesandbox example does not have any custom sorting logic at all, so not sure what the problem is. Also still not sure what you're trying to do.

**Comment by DhruvSakhiya** [comment] 2020-03-03 11:58
I removed customSort, when i click on 'date' column sort it's shows wrong sort result you can see on codesandbox.How can i fix this ?

**Comment by wdh2100** [comment] 2020-03-05 01:30
https://codesandbox.io/s/datesorting-fpgfi

**Comment by gabrielliwerant** [comment] 2020-03-05 01:44
Sorting date objects is probably weird. I have no idea how that would work. In order to sort dates, I would convert them to unix timestamps and sort them that way.

**Closed by gabrielliwerant** 2020-03-05 01:44 UTC
Labels: needs verification

**Comment by wdh2100** [comment] 2020-03-05 02:00
@gabrielliwerant 
How about adding date custom sort to the example?

The date data seems to be used a lot.

**Comment by gabrielliwerant** [comment] 2020-03-05 02:27
That's a fair request, but I'm a bit strapped for time these days, so it's not something I could promise soon, though I'd be open to a PR on it if you or someone else wants to provide that.

**Comment by DhruvSakhiya** [comment] 2020-03-05 04:23
@wdh2100 can i apply default sorting on other column while initial page is load. ? apart from date column ? and declared customSort @gabrielliwerant

**Comment by gabrielliwerant** [comment] 2020-03-05 15:40
`customSort` is one way, but you don't have to. If you use unix timestamps in your data, which I HIGHLY recommend, then you can simply use a `customRender` to convert it to whatever display format you want. Then your data will be sensible.

**Comment by mesh-newbie** [comment] 2020-03-11 04:22
"Now I may be as thick as a whale omelette", but even using a unix timestamp in the data (irrespective of making it look pretty with customBodyRender) will still result in the "Download CSV" showing the raw unix stamp (not the rendered onscreen value).
PS: Print shows the rendered version :-)

**Comment by gabrielliwerant** [comment] 2020-03-11 11:17
You have custom options for all of these things, so one way or another, you have to go custom somewhere. The table does not currently understand date objects.

**Comment by mesh-newbie** [comment] 2020-03-11 21:29
@gabrielliwerant its all good. Love your API... :-)

**Comment by gabrielliwerant** [comment] 2020-03-15 13:59
@mesh-newbie Haha, thanks, but I should mention that I did not start this project, and there have been many contributors, so I can't take full credit.

I do not believe so, but I would be open to a PR that would add this to one of the examples, or as a new example.
