### ISSUE TITLE
window is not defined after upgrade to v4 (mui-v5)

### ISSUE THREAD

**Issue by ozzyonfire** [gregnb/mui-datatables#1806] opened 2021-10-27 23:01 UTC
I upgraded to v4 and tried to load the page - I'm getting a "window is not defined" error. This is running on a NextJS project (SSR). 

## Expected Behavior

Table should load properly, even on SSR.

## Current Behavior

Page crashes. 
`ReferenceError: window is not defined
    at load (C:\Users\matto\Development\projects\tpl\node_modules\mui-datatables\dist\index.js:242:40)
    at new o (C:\Users\matto\Development\projects\tpl\node_modules\mui-datatables\dist\index.js:246:23382)
    at processChild (C:\Users\matto\Development\projects\tpl\node_modules\react-dom\cjs\react-dom-server.node.development.js:3305:14)
    at resolve (C:\Users\matto\Development\projects\tpl\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Users\matto\Development\projects\tpl\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Users\matto\Development\projects\tpl\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at renderToString (C:\Users\matto\Development\projects\tpl\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at renderPage (C:\Users\matto\Development\projects\tpl\node_modules\next\dist\next-server\server\render.js:53:854)
    at Object.ctx.renderPage (C:\Users\matto\Development\projects\tpl\.next\server\pages\_document.js:1214:26)
    at Function.getInitialProps (C:\Users\matto\Development\projects\tpl\.next\server\pages\_document.js:556:19)
`

Inspecting the code I get an error at this line.
`var load=function(e){return JSON.parse(window.localStorage.getItem(e))};`

## Steps to Reproduce (for bugs)

1. Next JS Project
2. Upgrade to mui5 and mui-datatables v4
3. Load a page

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 5.0.4 |
| MUI-datatables  | 4.0.0 |
| React        | 17.0.2 |
| browser      | chrome - 94.0.4606.81 |
| NextJS          | 11 |

**Comment by Cirelion** [comment] 2021-11-02 09:29
Any update or time estimation on this? @wdh2100

**Comment by ralphhaynes** [comment] 2021-11-06 02:27
A temporary work around I got working (oversimplified to only show the relevant parts):
```
import { Suspense } from 'react'
import dynamic from 'next/dynamic'
const MUIDataTable = dynamic(() => import('mui-datatables'), { suspense: true, ssr: false })

const DataTable = tableProps => (
	<Suspense fallback={<div className='loader' />}>
		<MUIDataTable {...tableProps} />
	</Suspense>
)
```
Something like that, but should help with some ideas to work with until it's fixed. Using Next.JS dynamic components might not be necessary if you aren't using Next.

Could maybe also try using `useState`/`useEffect` something like this:
```
const DataTable = tableProps => {
	const [ready, setReady] = useState(false)

	useEffect(() => {
		setReady(true)
	}, [])
	
	return (
		<>
			{ready && <MUIDataTable data={[]} columns={['name', 'other name']} />}
		</>
	)
}
```
Either way just find a way to make sure the MUIDataTable doesn't load server side.

**Comment by liamlows** [comment] 2021-11-12 02:39
I also found this issue when using Next.JS. I think because the code is rendered on the server side and has no access to window, it throws an undefined. To conditionally render the content only when the page is actually loaded on the client's web browser you can also do:

```
const DataTable = tableProps => {
  return (
    <>
      {typeof window !== 'undefined' && <MUIDataTable {...tableProps} />}
    </>
  )
}
```
and it should work well too. This was tested using @mui version 5.1 @datatables version 4.

**Comment by mahmoud2802** [comment] 2021-11-24 12:30
I have same Issue .
How can I fix That?

**Comment by zeknox** [comment] 2021-12-01 02:36
+1 having the same issue with nextjs

**Comment by wdh2100** [comment] 2022-02-20 12:52
fixed : https://github.com/gregnb/mui-datatables/pull/1870

**Comment by liamlows** [comment] 2022-02-22 20:09
Awesome just tested it out in v4 and all looks good to me! Not sure on v3 but if someone would like to speak to that this could probably be closed now @ozzyonfire

**Comment by busches** [comment] 2022-02-28 15:20
I can confirm this is fixed in V3 as well.

**Closed** 2022-04-25 15:14 UTC
Labels: bug, good first issue
