### ISSUE TITLE
Having problem with material ui laest version-4.4.1. When you are updating it's devDependencies to latest one??

### ISSUE THREAD

**Issue by archana-iron** [gregnb/mui-datatables#927] opened 2019-09-13 04:16 UTC
I am using latest version of material ui and having issue with this package.

**Comment by diegochavez** [comment] 2019-09-13 09:54
I guess we can start a new branch for releasing this project with the newer version, the only problem is are you planning to move to the next version here in this repository, We can help to this happen since we use the table heavily but we have plans to migrate to the newer version of MUI?

**Comment by gabrielliwerant** [comment] 2019-09-13 20:42
This library, and this repo will support mui v4, but I can't say exactly when because I don't know how long it will take to fix all of the issues from the migration. You and others can help by opening specific issues that occur with the table as you switch it from mui v3 to v4.

**Comment by gabrielliwerant** [comment] 2019-09-17 06:10
I'm closing the issue as there isn't anything here that is specifically actionable, but if you are having issues with mui v4 while using this library, feel free to open an issue with steps to reproduce and examples, and I will be glad to look into them.

**Closed by gabrielliwerant** 2019-09-17 06:10 UTC
