### ISSUE TITLE
Failed prop type: Invalid prop `isRowSelectable` of type `boolean` supplied to `TableSelectCell`, expected `function`.

### ISSUE THREAD

**Issue by tynindima** [gregnb/mui-datatables#1604] opened 2020-12-11 14:43 UTC
> 

> 
When I use your example in console appears error:
![image](https://user-images.githubusercontent.com/58040069/101915531-68a6dd80-3bce-11eb-9b31-5775d1e93ff6.png)
## Expected Behavior

Console without errors
## Current Behavior

"Warning: Failed prop type: Invalid prop `isRowSelectable` of type `boolean` supplied to `TableSelectCell`, expected `function`." appears in console
## Steps to Reproduce (for bugs)

1. npm install mui-datatables --save
2. npm install @material-ui/core
3. npm install @material-ui/icons
4. adding simple table 
![image](https://user-images.githubusercontent.com/58040069/101916498-ae17da80-3bcf-11eb-9ce1-24f27e8f0974.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.11.2     |
| MUI-datatables  |     3.7.2    |
| React        |     17.0.1    |
| browser      |    Chrome, Mozilla     |
| etc          |         |

**Comment by lounsbrough** [comment] 2020-12-11 22:38
We are having the same issue as of version 3.7.2

**Comment by lounsbrough** [comment] 2020-12-11 22:57
@tynindima - I have a PR up that should resolve this since it's causing issues for us as well.

**Comment by scarabcoder** [comment] 2020-12-11 23:16
I'm getting this issue with the latest version as well. 
I don't know if it's related, but I'm getting this error immediately before it:
![image](https://user-images.githubusercontent.com/4871271/101963508-c1bd4400-3bc3-11eb-87ff-e542eb42a5bb.png)

@lounsbrough Shouldn't it be a function though, and it's just being set to a bool incorrectly?

**Comment by lounsbrough** [comment] 2020-12-11 23:19
Yeah could be, not sure which is the expected behavior, but currently sibling components are providing booleans.

**Comment by scarabcoder** [comment] 2020-12-11 23:21
> Yeah could be, not sure which is the expected behavior, but currently sibling components are providing booleans.

I say that because `isRowSelectable` is in the API documentation as accepting a function. Seems like it should accept either a function or a boolean, but a more correct fix would probably be to supply `isRowSelectable` with something like `() => false`

**Comment by lounsbrough** [comment] 2020-12-11 23:24
True. I can make that change.

**Comment by wdh2100** [comment] 2020-12-11 23:33
@lounsbrough @scarabcoder 

Thanks!

Looking at the code, in `TableSelectCell` it should be set to Boolean.
The reason it is different from the document is that `TableSelectCell`  is an internally used component.

This problem will be resolved in 3.7.3.

**Comment by lounsbrough** [comment] 2020-12-11 23:35
I see @wdh2100 - I just reverted my last commit, I was thinking the same thing but wasn't sure which route was best.

**Closed** 2020-12-12 02:57 UTC
Labels: bug

**Comment by ShoaibMalik0000** [comment] 2022-12-02 12:15
![boolean](https://user-images.githubusercontent.com/114383005/205290775-87f3cc70-6a75-40cd-ad09-f929c8fb313d.PNG)
