### ISSUE TITLE
customFilterListRender in working

### ISSUE THREAD

**Issue by buddies2705** [gregnb/mui-datatables#582] opened 2019-04-27 08:42 UTC
I tried customFilterListRender in my application and it's now working, Then I tried the given [example](https://github.com/gregnb/mui-datatables/blob/master/examples/column-filters/index.js) in [codesandbox](https://codesandbox.io/embed/84w3wk98z2) itself which is also not working.

**Comment by gabrielliwerant** [comment] 2019-04-27 17:19
Can you be specific about what versions you're using and what is working or not working where? It looks like the latest release at the moment is `v2.0.0`, and it seems to work for me there.

**Comment by gabrielliwerant** [comment] 2019-05-02 00:36
This is what I see:

![capture](https://user-images.githubusercontent.com/1779564/57051725-d2b87c00-6c50-11e9-8a80-aed589241382.gif)

**Comment by gabrielliwerant** [comment] 2019-05-21 20:53
Closing this issue as it almost a month old, and I cannot verify what the problem is. If you spot a bug with `customFilterListRender ` you can open a new issue with the full steps to reproduce.

**Closed by gabrielliwerant** 2019-05-21 20:53 UTC
Labels: unverifiable
